### PR TITLE
WIP proposal of change #33

### PR DESCRIPTION
**Pull request by apupier**
- might need to update the version as I think it is breakign API
- no test in the project?
- there are 2 branches master and a 2.1.0 which has more commits. This
seems suspicious

### CODE REVIEW

**Comment by apupier** [comment]
@djelinek I cannot assign you

**Comment by djelinek** [comment]
> * might need to update the version as I think it is breaking API

Thank you for catching that

> * no test in the project?

not yet, at this time we are relying on vscode-extension-tester API tests but we want to provide tests for this package ASAP in next package releases

> * there are 2 branches master and a 2.1.0 which has more commits. This
>   seems suspicious

e.g. v2.1.0 is develop branch which contains new features for coming next release, it means that current released package version is master branch

**Review by mlorinc — APPROVED** [review]

**Comment by apupier** [comment]
it is saying that commit is blocked due to not signed commits. FOr most projects, I just need to add the signed-off -by without a specific pgp signature.
Can I let someone pick my modifications and report them with an account configured with signed commits? or to remove the restriction?

**Comment by djelinek** [comment]
> it is saying that commit is blocked due to not signed commits. FOr most projects, I just need to add the signed-off -by without a specific pgp signature.
> Can I let someone pick my modifications and report them with an account configured with signed commits? or to remove the restriction?

I removed this restriction

**Review by djelinek — APPROVED** [review]

**Pull request merged**
